version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - sammacbeth
  ignore:
  - dependency-name: "@types/chrome"
    versions:
    - 0.0.134
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.1
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: "@types/chai"
    versions:
    - 4.2.15
